# Copyright © 2026 Shenzhen Kaihong Digital Industry Development Co., Ltd.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Task-local Artifact collection for inbound DSoftBus Agent turns."""

from __future__ import annotations

import base64
import copy
import threading
import uuid
from collections.abc import Mapping
from contextvars import ContextVar, Token
from dataclasses import dataclass, field
from typing import Any

from . import protocol
from .a2a import A2AError, build_artifact_update


class TaskArtifactError(RuntimeError):
    """Stable failure raised before an Artifact enters a Task result."""

    def __init__(self, code: str) -> None:
        super().__init__(code)
        self.code = code


def _plain(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {str(key): _plain(item) for key, item in value.items()}
    if isinstance(value, (tuple, list)):
        return [_plain(item) for item in value]
    return copy.deepcopy(value)


@dataclass(slots=True)
class TaskArtifactCollector:
    """Thread-safe collector copied into AgentRunner and tool worker contexts."""

    task_id: str
    context_id: str
    _artifacts: list[dict[str, Any]] = field(default_factory=list, init=False)
    _lock: threading.Lock = field(default_factory=threading.Lock, init=False)

    def _append(self, candidate: Mapping[str, Any]) -> Mapping[str, Any]:
        try:
            event = build_artifact_update(
                task_id=self.task_id,
                context_id=self.context_id,
                artifact=candidate,
            )
        except A2AError as error:
            raise TaskArtifactError("INVALID_PARAMS") from error
        plain_event = _plain(event)
        if (
            len(protocol.canonical_json_bytes(plain_event))
            > protocol.TASK_STREAM_ITEM_BYTES_MAX
        ):
            raise TaskArtifactError("ARTIFACT_TOO_LARGE")
        normalized = plain_event["artifactUpdate"]["artifact"]
        with self._lock:
            # One slot is always reserved for the mandatory final-response
            # Artifact generated by DsoftbusTaskDispatcher.
            if len(self._artifacts) >= protocol.TASK_ARTIFACT_MAX - 1:
                raise TaskArtifactError("CAPACITY_BUSY")
            self._artifacts.append(normalized)
        return normalized

    def add_data(
        self,
        *,
        name: str,
        data: Any,
        description: str,
    ) -> Mapping[str, Any]:
        try:
            byte_length = len(protocol.canonical_json_bytes(data))
        except (protocol.ProtocolError, TypeError, ValueError) as error:
            raise TaskArtifactError("INVALID_PARAMS") from error
        if byte_length > protocol.TASK_SINGLE_FRAME_ARTIFACT_BYTES_MAX:
            raise TaskArtifactError("ARTIFACT_TOO_LARGE")
        return self._append(
            {
                "artifactId": str(uuid.uuid4()),
                "name": name,
                "description": description,
                "parts": [
                    {
                        "data": _plain(data),
                        "filename": name,
                        "mediaType": "application/json",
                    }
                ],
                "metadata": {"mclaw.artifactRole": "task-output"},
            }
        )

    def add_raw(
        self,
        *,
        name: str,
        raw: bytes,
        media_type: str,
        description: str,
    ) -> Mapping[str, Any]:
        if not isinstance(raw, bytes) or not raw:
            raise TaskArtifactError("INVALID_PARAMS")
        if len(raw) > protocol.TASK_SINGLE_FRAME_ARTIFACT_BYTES_MAX:
            raise TaskArtifactError("ARTIFACT_TOO_LARGE")
        return self._append(
            {
                "artifactId": str(uuid.uuid4()),
                "name": name,
                "description": description,
                "parts": [
                    {
                        "raw": base64.b64encode(raw).decode("ascii"),
                        "filename": name,
                        "mediaType": media_type,
                    }
                ],
                "metadata": {"mclaw.artifactRole": "task-output"},
            }
        )

    def snapshot(self) -> tuple[Mapping[str, Any], ...]:
        with self._lock:
            return tuple(_plain(value) for value in self._artifacts)


_CURRENT_COLLECTOR: ContextVar[TaskArtifactCollector | None] = ContextVar(
    "mclaw_dsoftbus_task_artifact_collector",
    default=None,
)


def bind_task_artifact_collector(
    collector: TaskArtifactCollector,
) -> Token[TaskArtifactCollector | None]:
    return _CURRENT_COLLECTOR.set(collector)


def reset_task_artifact_collector(
    token: Token[TaskArtifactCollector | None],
) -> None:
    _CURRENT_COLLECTOR.reset(token)


def get_task_artifact_collector() -> TaskArtifactCollector | None:
    return _CURRENT_COLLECTOR.get()


__all__ = [
    "TaskArtifactCollector",
    "TaskArtifactError",
    "bind_task_artifact_collector",
    "get_task_artifact_collector",
    "reset_task_artifact_collector",
]
